import{a as p,S as b,i as L}from"./assets/vendor-C4-ZuMk8.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))i(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&i(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function i(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const w="46892237-a54e01ec2b73ea1c4de56cebe",S="https://pixabay.com/api/",v=15;async function _(e,o=1){try{return(await p.get(S,{params:{key:w,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,page:o,per_page:v}})).data}catch(n){throw console.error("Error fetching images:",n),n}}let d;function q(){d=new b(".gallery a",{captionDelay:250})}function E(e){const o=document.querySelector(".gallery"),n=e.map(({webformatURL:i,largeImageURL:t,tags:r,likes:a,views:y,comments:h,downloads:g})=>`
    <a href="${t}" class="gallery__link">
      <div class="gallery__item">
        <img src="${i}" alt="${r}" loading="lazy"/>
        <div class="gallery__info">
          <p><b>Likes:</b> ${a}</p>
          <p><b>Views:</b> ${y}</p>
          <p><b>Comments:</b> ${h}</p>
          <p><b>Downloads:</b> ${g}</p>
        </div>
      </div>
    </a>
  `).join("");o.insertAdjacentHTML("beforeend",n),d.refresh()}function M(){document.querySelector(".gallery").innerHTML=""}function P(){document.querySelector(".load-more").classList.remove("hidden")}function f(){document.querySelector(".load-more").classList.add("hidden")}function s(e){L.info({title:"Info",message:e})}let l="",c=1,u=0;document.addEventListener("DOMContentLoaded",()=>{q();const e=document.querySelector(".search-form"),o=document.querySelector(".load-more");e.addEventListener("submit",A),o.addEventListener("click",O)});async function A(e){if(e.preventDefault(),l=e.currentTarget.elements.searchQuery.value.trim(),l===""){s("Please enter a search query.");return}c=1,M(),f(),await m()}async function O(){c+=1,await m(),T()}async function m(){try{const{hits:e,totalHits:o}=await _(l,c);if(e.length===0){s("Sorry, no images found. Try again!");return}u=o,E(e),c*15<u?P():(f(),s("We're sorry, but you've reached the end of search results."))}catch{s("An error occurred while fetching images. Please try again.")}}function T(){const{height:e}=document.querySelector(".gallery__item").getBoundingClientRect();window.scrollBy({top:e*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
