import{a as g,S as b,i as l}from"./assets/vendor-Rdv7LHNr.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const u of s.addedNodes)u.tagName==="LINK"&&u.rel==="modulepreload"&&r(u)}).observe(document,{childList:!0,subtree:!0});function i(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=i(t);fetch(t.href,s)}})();const L="46892237-a54e01ec2b73ea1c4de56cebe",w="https://pixabay.com/api/";async function f(o,e=1,i=15){try{return(await g.get(w,{params:{key:L,q:o,image_type:"photo",orientation:"horizontal",safesearch:!0,page:e,per_page:i}})).data}catch(r){throw console.error("Error fetching images:",r),r}}let p;function m(o,e){const i=o.map(r=>`
<a href="${r.largeImageURL}" class="gallery-item">
<img src="${r.webformatURL}" alt="${r.tags}" loading="lazy"/>
<div class="image-info">
<p><b>Likes:</b> ${r.likes}</p>
<p><b>Views:</b> ${r.views}</p>
<p><b>Comments:</b> ${r.comments}</p>
<p><b>Downloads:</b> ${r.downloads}</p>
</div>
</a>`).join("");e.insertAdjacentHTML("beforeend",i),p?p.refresh():p=new b(".gallery-item",{captionsData:"alt",captionDelay:250})}const E=document.querySelector("#search-form"),y=document.querySelector(".gallery"),a=document.querySelector(".loader"),n=document.querySelector(".load-more");let d="",c=1,h=0;E.addEventListener("submit",async o=>{if(o.preventDefault(),d=o.currentTarget.elements.query.value.trim(),!d){l.error({title:"Error",message:"Please enter a search term"});return}y.innerHTML="",c=1,n.style.display="none",a.style.display="block";try{const e=await f(d,c);if(a.style.display="none",h=e.totalHits,e.hits.length===0){l.info({message:"No images found. Try a different query!"});return}m(e.hits,y),e.totalHits>e.hits.length&&(n.style.display="block")}catch(e){a.style.display="none",l.error({title:"Error",message:e.message})}});n.addEventListener("click",async()=>{c+=1,a.style.display="block",n.style.display="none";try{const o=await f(d,c);a.style.display="none",m(o.hits,y),c*15>=h?(n.style.display="none",l.info({message:"We're sorry, but you've reached the end of search results."})):n.style.display="block",v()}catch(o){a.style.display="none",l.error({title:"Error",message:o.message})}});function v(){const{height:o}=y.firstElementChild.getBoundingClientRect();window.scrollBy({top:o*2,behavior:"smooth"})}
//# sourceMappingURL=index.js.map
